import React from 'react'
import LogIn from '@/components/Login'

const LoginWrapper = () => {
  return (
    <div>
      <LogIn/>
    </div>
  )
}

export default LoginWrapper



export const metadata = {
  title: "LogIn",
  description: "Generated by create next app",
};