"use client"

import React from 'react'
import Dashboard from '@/components/Dashboard'
import { useEffect } from 'react';
const DashboardWrapper = () => {
  useEffect(() => {
    document.title="Fan Fund " // Now it runs only in the browser
  }, []);
  return (
    <div>
      <Dashboard/>
    </div>
  )
}

export default DashboardWrapper


// export const metadata = {
//   title: "Dashboard",
//   description: "Generated by create next app",
// };