import React from 'react'
import Dashboard from '@/components/Dashboard'
const DashboardWrapper = () => {
  return (
    <div>
      <Dashboard/>
    </div>
  )
}

export default DashboardWrapper


export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};